### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by choonho** [SpringWiz11/myplugin#1]
I think you missed to commit the source.

**Comment by choonho** [comment]
@SpringWiz11 see the best practice examples.

https://github.com/orgs/cloudforet-io/discussions/137

![image](https://github.com/SpringWiz11/myplugin/assets/3993088/995f2d0e-fc55-42f2-97a3-05fa5e4db985)

**Comment by SpringWiz11** [comment]
Hi @choonho,

Could you please share the updates and corrections that has to be done?

**Comment by SpringWiz11** [comment]
Sure sir, 
Thank you very much

**Comment by SpringWiz11** [comment]
Hi @choonho,

I have commited the content into the master branch.

I am attaching the picture for your reference.
![Screenshot from 2024-01-08 23-16-42](https://github.com/SpringWiz11/myplugin/assets/102406442/64774a5f-7191-48f8-a489-321ca81ad080)

Regards,
Kishan

**Comment by choonho** [comment]
@SpringWiz11 Got it. You have two confusing branches, main and master. Master branch is old convention, main branch is better than master.

**Comment by SpringWiz11** [comment]
I am sorry for the confusion. I will make sure I wont be repeating this next time onwards.
